
setTimeout(()=>document.getElementById('loader').classList.add('hide'),800);
const tr=document.documentElement.lang==='tr';
function v(id){return Math.max(0,parseFloat(document.getElementById(id).value)||0)}
function show(id,html){const e=document.getElementById(id);e.innerHTML=html+`<div class="result-actions"><button class="smallbtn whatsapp" onclick="share('${id}')">${tr?"WhatsApp'ta Paylaş":"Share on WhatsApp"}</button><button class="smallbtn" onclick="window.print()">${tr?"PDF / Yazdır":"PDF / Print"}</button></div>`;e.style.display='block'}
function share(id){const text=encodeURIComponent((tr?"Gold Fish Oranda Ankara Hesaplama Sonucu":"Gold Fish Oranda Ankara Calculation Result")+":\n"+document.getElementById(id).innerText+"\nhttps://hesap.goldfishoranda.com");window.open("https://wa.me/?text="+text,"_blank")}
function filterCards(){const q=document.getElementById('search').value.toLowerCase();document.querySelectorAll('.searchable').forEach(c=>c.style.display=c.innerText.toLowerCase().includes(q)||c.dataset.name.includes(q)?'block':'none')}
function feedCalc(){const d=v('fishCount')*parseFloat(document.getElementById('fishSize').value),m=v('meals')||1;show('feedResult',tr?`🐟 Günlük toplam yem: <b>${d.toFixed(2)} g</b><br>🍽️ Öğün başı: <b>${(d/m).toFixed(2)} g</b><br>✅ Gold Fish Bait %56 Protein önerilir.`:`🐟 Daily total food: <b>${d.toFixed(2)} g</b><br>🍽️ Per meal: <b>${(d/m).toFixed(2)} g</b><br>✅ Gold Fish Bait 56% Protein is recommended.`)}
function volumeCalc(){const g=v('l')*v('w')*v('h')/1000;show('volumeResult',tr?`📏 Brüt hacim: <b>${g.toFixed(0)} L</b><br>💧 Yaklaşık net su: <b>${(g*.85).toFixed(0)} L</b><br>🌊 Önerilen filtre debisi: <b>${(g*.85*7).toFixed(0)} L/saat</b>`:`📏 Gross volume: <b>${g.toFixed(0)} L</b><br>💧 Approx. net water: <b>${(g*.85).toFixed(0)} L</b><br>🌊 Recommended filter flow: <b>${(g*.85*7).toFixed(0)} L/h</b>`)}
function saltCalc(){const a=v('saltLiter')*parseFloat(document.getElementById('saltDose').value);show('saltResult',tr?`🧂 Toplam tuz: <b>${a.toFixed(0)} g</b>`:`🧂 Total salt: <b>${a.toFixed(0)} g</b>`)}
function waterCalc(){const a=v('waterLiter')*parseFloat(document.getElementById('waterRate').value);show('waterResult',tr?`💦 Haftalık su değişimi: <b>${a.toFixed(0)} L</b>`:`💦 Weekly water change: <b>${a.toFixed(0)} L</b>`)}
function flowCalc(){const a=v('flowLiter')*parseFloat(document.getElementById('turnover').value);show('flowResult',tr?`🌊 Önerilen filtre debisi: <b>${a.toFixed(0)} L/saat</b>`:`🌊 Recommended filter flow: <b>${a.toFixed(0)} L/h</b>`)}
function doseCalc(){const a=v('doseLiter')/100*parseFloat(document.getElementById('doseProduct').value);show('doseResult',tr?`🧪 Tavsiye edilen doz: <b>${a.toFixed(1)} ml</b><br>Etiket talimatını ayrıca kontrol edin.`:`🧪 Suggested dose: <b>${a.toFixed(1)} ml</b><br>Always check label instructions.`)}
function fishDoctor(){let r=[]; if(document.getElementById('sBottom').checked)r.push(tr?'Stres veya su kalitesi problemi':'Stress or water quality issue'); if(document.getElementById('sNoEat').checked)r.push(tr?'Stres, yeni ortam veya hastalık başlangıcı':'Stress, new environment or early illness'); if(document.getElementById('sWhite').checked)r.push(tr?'Beyaz benek / dış parazit ihtimali':'Possible white spot / external parasite'); if(document.getElementById('sGill').checked)r.push(tr?'Amonyak, nitrit veya oksijen problemi':'Possible ammonia, nitrite or oxygen issue'); if(document.getElementById('sCloudy').checked)r.push(tr?'Bakteri patlaması veya fazla yemleme':'Bacterial bloom or overfeeding'); if(!r.length)r.push(tr?'Belirti seçilmedi; rutin bakım önerilir.':'No symptom selected; routine care is recommended.'); const liter=v('diagLiter')||100; const wc=document.getElementById('sGill').checked||document.getElementById('sCloudy').checked?40:30; document.getElementById('doctor').innerHTML=`<h3>${tr?'Ön Bakım Planı':'Pre-Care Plan'}</h3><p><b>${tr?'Olası nedenler':'Possible causes'}:</b></p><ul>${r.map(x=>`<li>${x}</li>`).join('')}</ul><p><b>${tr?'Bugün önerilen su değişimi':'Recommended water change today'}:</b> %${wc} - ${Math.round(liter*wc/100)} L</p><p><b>Easy-Life:</b> AquaMaker + Filter Medium</p><p><b>Gold Fish Bait:</b> ${tr?'Az ve kontrollü yemleme.':'Feed lightly and carefully.'}</p><div class="result-actions"><button class="smallbtn whatsapp" onclick="shareDoctor()">${tr?"WhatsApp'ta Paylaş":"Share on WhatsApp"}</button><button class="smallbtn" onclick="window.print()">${tr?'PDF / Yazdır':'PDF / Print'}</button></div>`}
function shareDoctor(){const text=encodeURIComponent((tr?'Balığıma Ne Oldu? Ön Bakım Planı':'What’s Wrong With My Fish? Pre-Care Plan')+":\n"+document.getElementById('doctor').innerText+"\nhttps://hesap.goldfishoranda.com");window.open("https://wa.me/?text="+text,"_blank")}
